### ISSUE TITLE
Generate Database Scripts: NullPointerException

### ISSUE THREAD

**Issue by LionelWolf** [cuba-platform/sample-library-cuba7#1]
I installed the CUBA plugin in IDEA,downloaded this project,and imported  it  into IDEA.The Database type is Mysql,Database connection is normal.When I clicked 'Generate Database Scripts' threw an exception: NullPointerException.The log details are as follows:

2019-02-22 17:51:04,480 [33707356]   WARN - ndling.DefaultExceptionHandler - Studio error: 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.haulmont.studio.backend.ed.datatypes.CustomDatatype.getSqlType(SourceFile:50)
	at com.haulmont.studio.backend.ed.ddl.AbstractDdlGenerator.getMappedType(SourceFile:1600)
	at com.haulmont.studio.backend.ed.ddl.MysqlDdlGenerator.getMappedType(SourceFile:165)
	at com.haulmont.studio.backend.ed.ddl.AbstractDdlGenerator.generateColumn(SourceFile:1196)
	at com.haulmont.studio.backend.ed.ddl.AbstractDdlGenerator.getColumnDefinition(SourceFile:942)
	at com.haulmont.studio.backend.ed.ddl.TableGenerator.processRestPersistentAttributes(SourceFile:143)
	at com.haulmont.studio.backend.ed.ddl.TableGenerator.processing(SourceFile:79)
	at com.haulmont.studio.backend.ed.ddl.AbstractDdlGenerator.generateTable(SourceFile:305)
	at com.haulmont.studio.backend.ed.ddl.AbstractDdlGenerator.generateInitDdl(SourceFile:145)
	at com.haulmont.studio.backend.ed.ddl.TableUpdatesGenerator.processing(SourceFile:112)
	at com.haulmont.studio.backend.ed.ddl.AbstractDdlGenerator.generateTableUpdates(SourceFile:492)
	at com.haulmont.studio.backend.ed.ddl.AbstractDdlGenerator.generateUpdates(SourceFile:481)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:592)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Has anyone encountered this situation ?What causes it ?
Thank you !

**Comment by alexbudarov** [comment]
Please report all CUBA Studio errors to the support forum: 
https://www.cuba-platform.com/discuss/
